"""Presentation-only reporting for one IEEE 802.3 Annex 178A COM run."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import numpy as np

from .com_model_178A import (
    COMAdcInputPMF,
    COMConfig,
    COMDTEStatus,
    COMImpStageStatus,
    COMStatus,
)
from .pmf_handler import Pmf1D


class COMReport178A:
    """
    Plot the status generated by one completed 178A COM run.

    This class owns presentation only. It never recalculates a COM quantity or
    mutates ``cfg`` / ``status``. Figures are organized by the same stage
    boundaries used by ``COM._run_once()``.
    """

    def __init__(self, cfg: COMConfig, status: COMStatus):
        self.cfg = cfg
        self.status = status

    # ------------------------------------------------------------------
    # Shared plot helpers
    # ------------------------------------------------------------------
    @staticmethod
    def _plt() -> Any:
        import matplotlib.pyplot as plt

        return plt

    @staticmethod
    def _save_path(directory: str | Path, filename: str) -> str:
        if not directory:
            return ""
        path = Path(directory)
        path.mkdir(parents=True, exist_ok=True)
        return str(path / filename)

    def _subplots(
        self,
        directory: str | Path,
        filename: str,
        *args: Any,
        **kwargs: Any,
    ) -> tuple[Any, Any, str]:
        """Create a report figure without changing the caller's pyplot backend."""
        output_path = self._save_path(directory, filename)
        if output_path:
            from matplotlib.backends.backend_agg import FigureCanvasAgg
            from matplotlib.figure import Figure

            figsize = kwargs.pop("figsize", None)
            fig = Figure(figsize=figsize)
            FigureCanvasAgg(fig)
            axes = fig.subplots(*args, **kwargs)
            return fig, axes, output_path
        fig, axes = self._plt().subplots(*args, **kwargs)
        return fig, axes, output_path

    def _finish(self, fig: Any, output_path: str) -> None:
        fig.tight_layout()
        if output_path:
            fig.savefig(output_path, bbox_inches="tight")
        else:
            fig.canvas.draw_idle()
            self._plt().show()

    def _config_note(self) -> str:
        return (
            f"fb/2={self.cfg.link.fb / 2e9:.3f} GHz, "
            f"OSR={self.cfg.link.per_ui}, "
            f"df={self.cfg.link.df / 1e6:.3f} MHz"
        )

    def _annotate_pmf_config(self, ax: Any, adc: COMAdcInputPMF) -> None:
        """Annotate a PMF plot with its resolved amplitude-grid settings."""
        pmf = adc.p_s or adc.p_sn or adc.p_n or adc.p_ga
        if pmf is None:
            return
        self._annotate_pmf_settings(ax, pmf)

    def _annotate_pmf_settings(self, ax: Any, pmf: Any) -> None:
        """Annotate a PMF plot with its resolved amplitude-grid settings."""
        keep_mass = float(self.cfg.pmf.keep_mass)
        missing_mass = max(0.0, 1.0 - keep_mass)
        if missing_mass > 0.0:
            exponent = int(round(np.log10(missing_mass)))
            keep_text = f"1-1e{exponent}"
        else:
            keep_text = "1"
        ax.text(
            0.01,
            0.02,
            f"dy={pmf.dx:.3e} V, keep_mass={keep_text}",
            transform=ax.transAxes,
            ha="left",
            va="bottom",
            fontsize=8,
            bbox={"facecolor": "white", "alpha": 0.85, "edgecolor": "0.6", "pad": 2.0},
        )

    @staticmethod
    def _pmf_moments(pmf: Any) -> tuple[float, float]:
        x = np.asarray(pmf.x, dtype=float)
        mass = np.asarray(pmf.pmf, dtype=float)
        mu = float(np.sum(x * mass))
        variance = float(np.sum((x - mu) ** 2 * mass))
        return mu, float(np.sqrt(max(0.0, variance)))

    @staticmethod
    def _relative_gain_db(segment: Any, frequency_hz: float) -> Optional[float]:
        """Return transfer-function gain relative to DC, or None if unavailable."""
        if frequency_hz < float(segment.freqs[0]) or frequency_hz > float(segment.freqs[-1]):
            return None
        magnitude_db = 20.0 * np.log10(np.maximum(np.abs(segment.tf), np.finfo(float).tiny))
        return float(np.interp(frequency_hz, segment.freqs, magnitude_db - magnitude_db[0]))

    def _il_at_f_nyq(self, model: Any) -> Optional[float]:
        frequency_hz = self.cfg.link.fb / 2.0
        if frequency_hz < float(model.freqs[0]) or frequency_hz > float(model.freqs[-1]):
            return None
        il_db = 20.0 * np.log10(np.maximum(np.abs(model.sdd21), np.finfo(float).tiny))
        return float(np.interp(frequency_hz, model.freqs, il_db))

    def _il_f_nyq_subtitle(self, model: Any) -> str:
        value = self._il_at_f_nyq(model)
        if value is None:
            return "IL @ f_nyq = outside measured band"
        return f"IL @ f_nyq = {value:.2f} dB"

    def _annotate_step_transition(self, ax: Any, segment: Any) -> None:
        """Mark the measured 20%-80% transition interval on a step plot."""
        sr = np.asarray(segment.sr, dtype=float)
        main_index = int(np.argmax(np.abs(segment.ir)))
        x_ui = (np.asarray(segment.times) - segment.times[main_index]) * self.cfg.link.fb
        y0 = float(np.nanmin(sr))
        y1 = float(np.nanmax(sr))
        span = y1 - y0
        if not np.isfinite(span) or span <= 0.0:
            return

        def crossing(level: float) -> Optional[float]:
            indices = np.flatnonzero(sr >= level)
            if indices.size == 0:
                return None
            index = int(indices[0])
            if index == 0:
                return float(x_ui[0])
            x0, x1 = float(x_ui[index - 1]), float(x_ui[index])
            v0, v1 = float(sr[index - 1]), float(sr[index])
            if np.isclose(v0, v1):
                return x1
            return x0 + (level - v0) * (x1 - x0) / (v1 - v0)

        y20 = y0 + 0.2 * span
        y80 = y0 + 0.8 * span
        x20 = crossing(y20)
        x80 = crossing(y80)
        if x20 is None or x80 is None:
            return
        ax.axhline(y20, linestyle=":", color="tab:gray", linewidth=1.0)
        ax.axhline(y80, linestyle=":", color="tab:gray", linewidth=1.0)
        ax.axvline(x20, linestyle="--", color="tab:red", linewidth=1.0)
        ax.axvline(x80, linestyle="--", color="tab:red", linewidth=1.0)
        ax.annotate(
            f"20%-80% = {x80 - x20:.3g} UI",
            xy=((x20 + x80) / 2.0, y80),
            xytext=(8, 8),
            textcoords="offset points",
            color="tab:red",
            fontsize=9,
        )

    def _annotate_config(self, ax: Any) -> None:
        ax.text(
            0.01,
            0.01,
            self._config_note(),
            transform=ax.transAxes,
            ha="left",
            va="bottom",
            fontsize=8,
            bbox={"boxstyle": "round,pad=0.25", "facecolor": "white", "alpha": 0.8},
        )

    def _annotate_imp_config(self, ax: Any) -> None:
        """Annotate impairment plots with the physical impairment inputs."""
        imp = self.cfg.imp
        lines = [
            f"R_LM={imp.R_LM:.4g}",
            f"SNR_TX={imp.SNR_TX:.3g} dB",
            f"sigma_RJ={imp.sigma_RJ:.3e} UI",
            f"A_DD={imp.A_DD:.3e} UI",
            f"eta_0={imp.eta_0:.3e} V^2/Hz",
        ]
        if imp.N_qb is not None:
            lines.append(f"N_qb={imp.N_qb}")
        if imp.P_qc is not None:
            lines.append(f"P_qc={imp.P_qc:.3e}")
        ax.text(
            0.01,
            0.01,
            "\n".join(lines),
            transform=ax.transAxes,
            ha="left",
            va="bottom",
            fontsize=8,
            bbox={"boxstyle": "round,pad=0.25", "facecolor": "white", "alpha": 0.85},
        )

    def _title(self, ax: Any, title: str, subtitle: str = "") -> None:
        ax.set_title(title, fontsize=14, pad=20 if subtitle else 8)
        if subtitle:
            ax.text(
                0.5,
                1.01,
                subtitle,
                transform=ax.transAxes,
                ha="center",
                va="bottom",
                fontsize=9,
                color="0.3",
            )

    def _path_directory(self, root: str | Path, path_idx: int) -> str:
        if not root:
            return ""
        path = self.status.paths[path_idx]
        name = "path_victim" if path_idx == 0 and path.kind == "victim" else f"path_{path_idx:02d}_{path.kind}"
        return str(Path(root) / name)

    def _frequency_xlim(self, freqs: np.ndarray) -> tuple[float, float]:
        hi = min(float(freqs[-1]), 1.1 * float(self.cfg.link.fb))
        return (0.0, hi)

    @staticmethod
    def _available(stage: Optional[COMImpStageStatus]) -> bool:
        return stage is not None

    # ------------------------------------------------------------------
    # build_all_paths: COMPath
    # ------------------------------------------------------------------
    def plot_path(self, path_idx: int = 0, save_path: str | Path = "") -> dict[str, str]:
        """Plot S-parameter, continuous-time response, and pulse fields of one COMPath."""
        if path_idx < 0 or path_idx >= len(self.status.paths):
            raise IndexError("path_idx is outside COMStatus.paths.")

        path = self.status.paths[path_idx]
        out_dir = self._path_directory(save_path, path_idx)
        label = f"{path_idx:02d}_{path.kind}"
        outputs: dict[str, str] = {}

        for field_name, model, subtitle in (
            ("S_tx", path.S_tx, "TX package Sdd"),
            ("S_ch", path.S_ch, "Measured channel Sdd"),
            ("S_rx", path.S_rx, "RX package Sdd"),
            ("S_all", path.S_all, "Cascaded Sdd path"),
        ):
            fig, ax, output = self._subplots(out_dir, f"{field_name}_sdd.png")
            model.plot_sdd(ax=ax, xlim=self._frequency_xlim(model.freqs))
            self._title(ax, f"{label} {field_name}", subtitle)
            self._annotate_config(ax)
            self._finish(fig, output)
            outputs[field_name] = output

        for field_name, model in (("S_ch", path.S_ch), ("S_all", path.S_all)):
            fig, ax, output = self._subplots(out_dir, f"{field_name}_IL.png")
            model.plot_IL(
                ax=ax,
                xlim=self._frequency_xlim(model.freqs),
            )
            self._title(
                ax,
                f"{label} {field_name} IL",
                f"Sdd21 insertion loss; {self._il_f_nyq_subtitle(model)}",
            )
            self._annotate_config(ax)
            self._finish(fig, output)
            outputs[f"{field_name}_IL"] = output

        filter_subtitles = {
            "H_ffe": f"txfir={np.asarray(self.cfg.filter.txfir).tolist()}",
            "H_t": f"Tr={self.cfg.filter.Tr * 1e12:.4g} ps",
            "H_21": (
                "Terminated voltage transfer function; "
                f"IL @ f_nyq = {self._relative_gain_db(path.H_21, self.cfg.link.fb / 2.0):.2f} dB"
                if self._relative_gain_db(path.H_21, self.cfg.link.fb / 2.0) is not None
                else "Terminated voltage transfer function; IL @ f_nyq = outside measured band"
            ),
            "H_r": f"3dB BW: fr={self.cfg.filter.fr / 1e9:.4g} GHz",
            "H_ctf": (
                f"zeros: fz1={self.cfg.filter.f_z1 / 1e9:.4g} GHz, "
                f"fz2={self.cfg.filter.f_z2 / 1e9:.4g} GHz; "
                f"poles: fp1={self.cfg.filter.f_p1 / 1e9:.4g} GHz, "
                f"fp2={self.cfg.filter.f_p2 / 1e9:.4g} GHz, "
                f"fp3={self.cfg.filter.f_p3 / 1e9:.4g} GHz"
            ),
            "H_all": "All continuous-time filters cascaded",
        }
        for field_name, segment in (
            ("H_ffe", path.H_ffe),
            ("H_t", path.H_t),
            ("H_21", path.H_21),
            ("H_r", path.H_r),
            ("H_ctf", path.H_ctf),
            ("H_all", path.H_all),
        ):
            fig, ax, output = self._subplots(out_dir, f"{field_name}_tf.png")
            segment.plot_tf(
                ax=ax,
                x_scale="linear",
                xlim=self._frequency_xlim(segment.freqs),
            )
            if field_name == "H_r":
                f_r = self.cfg.filter.fr
                if f_r is not None and segment.freqs[0] <= f_r <= segment.freqs[-1]:
                    segment.annotate_f(ax, f_r)
            if field_name == "H_all":
                il_nyq = self._relative_gain_db(segment, self.cfg.link.fb / 2.0)
                filter_subtitles[field_name] = (
                    "All continuous-time filters cascaded; "
                    + (
                        f"IL @ f_nyq = {il_nyq:.2f} dB"
                        if il_nyq is not None
                        else "IL @ f_nyq = outside measured band"
                    )
                )
            self._title(ax, f"{label} {field_name}", filter_subtitles[field_name])
            if field_name != "H_ctf":
                self._annotate_config(ax)
            self._finish(fig, output)
            outputs[field_name] = output

        for field_name, segment, xlim in (
            ("H_t_sr", path.H_t, (-0.5, 1.5)),
            ("H_21_ir", path.H_21, (-5.0, 20.0)),
            ("pulse_ir", path.pulse, (-5.0, 20.0)),
        ):
            fig, ax, output = self._subplots(out_dir, f"{field_name}.png")
            if field_name == "H_t_sr":
                segment.plot_sr(ax=ax, x_unit="ui", x_origin="max", xlim_ui=xlim)
                self._annotate_step_transition(ax, segment)
                subtitle = f"Tr={self.cfg.filter.Tr * 1e12:.4g} ps (20%-80%)"
            else:
                segment.plot_ir(ax=ax, x_unit="ui", x_origin="max", xlim_ui=xlim)
                subtitle = ""
            self._title(ax, f"{label} {field_name}", subtitle)
            self._annotate_config(ax)
            self._finish(fig, output)
            outputs[field_name] = output

        return outputs

    # ------------------------------------------------------------------
    # sampling-phase sweep / MMSE-DTE: COMRunStatus + COMDTEStatus
    # ------------------------------------------------------------------
    def plot_phase_dte(self, save_path: str | Path = "") -> dict[str, str]:
        """Plot sampling-phase selection and selected MMSE-DTE fields."""
        if self.status.dfe is None or self.status.run is None:
            raise ValueError("COMStatus.run and COMStatus.dfe are required for DTE reporting.")
        dte = self.status.dfe
        out_dir = str(Path(save_path) / "phase_dte") if save_path else ""
        outputs: dict[str, str] = {}

        fig, ax, output = self._subplots(out_dir, "mse_by_pos.png")
        run = self.status.run
        mse = np.asarray([np.nan if value is None else value for value in run.mse_by_pos], dtype=float)
        pos = np.arange(len(mse))
        coarse_pos = np.asarray(run.coarse_pos, dtype=int)
        fine_pos = np.asarray(run.fine_pos, dtype=int)
        if fine_pos.size:
            coarse_valid = coarse_pos[np.isfinite(mse[coarse_pos])]
            fine_valid = fine_pos[np.isfinite(mse[fine_pos])]
            if coarse_valid.size:
                ax.plot(
                    coarse_valid, mse[coarse_valid], marker="o", linewidth=1.0,
                    color="tab:blue", label="coarse MSE",
                )
            if fine_valid.size:
                ax.plot(
                    fine_valid, mse[fine_valid], marker="s", linewidth=1.0,
                    color="tab:orange", label="fine MSE",
                )
        else:
            valid = np.isfinite(mse)
            ax.plot(pos[valid], mse[valid], marker="o", linewidth=1.0, label="valid MSE")
        invalid = np.asarray([message is not None for message in self.status.run.main_cursor_error_by_pos])
        if np.any(invalid):
            y_mark = np.nanmax(mse) if np.any(np.isfinite(mse)) else 0.0
            ax.scatter(
                pos[invalid], np.full(np.count_nonzero(invalid), y_mark),
                marker="x", color="tab:red", label="main-cursor error",
            )
        ax.axvline(dte.pos, color="tab:green", linestyle="--", label=f"selected pos={dte.pos}")
        ax.set_xlabel("Sampling phase pos")
        ax.set_ylabel("MMSE (V^2)")
        ax.grid(True)
        ax.legend()
        subtitle = (
            "Coarse phase sweep followed by fine search"
            if fine_pos.size
            else "MSE is minimized over valid phases only"
        )
        self._title(ax, "Sampling Phase Search", subtitle)
        self._annotate_config(ax)
        self._finish(fig, output)
        outputs["mse_by_pos"] = output

        pre = self.status.imp.pre_dte if self.status.imp is not None else None
        if pre is not None and pre.eq_ch is not None and pre.eq_ch.h_dsamp is not None:
            victim_pulse = self.status.paths[0].pulse if self.status.paths else None
            if victim_pulse is not None:
                outputs["h_dsamp"] = self._plot_pulse_and_h_dsamp(
                    victim_pulse.ir,
                    pre.eq_ch.h_dsamp,
                    dte,
                    out_dir,
                )
            else:
                outputs["h_dsamp"] = self._plot_sequence(
                    pre.eq_ch.h_dsamp,
                    out_dir,
                    "h_dsamp.png",
                    "Selected h_dsamp",
                    "h_dsamp (V)",
                    reference_index=int(dte.d) - int(self.cfg.dte.d_w),
                )

        outputs["coefficients"] = self._plot_dte_coefficients(dte, out_dir)
        outputs["mmse_matrices"] = self._plot_dte_matrices(dte, out_dir)
        return outputs

    def _plot_pulse_and_h_dsamp(
        self,
        pulse_ir: np.ndarray,
        h_dsamp: np.ndarray,
        dte: COMDTEStatus,
        directory: str,
    ) -> str:
        """Overlay the CT pulse and selected DT samples on one time frame."""
        pulse_ir = np.asarray(pulse_ir, dtype=float)
        h_dsamp = np.asarray(h_dsamp, dtype=float)
        per_ui = int(self.cfg.link.per_ui)
        pulse_index = np.arange(len(pulse_ir), dtype=float)
        dt_index = np.arange(len(h_dsamp), dtype=float) * per_ui + float(dte.pos)
        x_pulse = (pulse_index - float(dte.ts)) / per_ui
        x_dsamp = (dt_index - float(dte.ts)) / per_ui

        fig, ax, output = self._subplots(directory, "h_dsamp.png")
        ax.plot(x_pulse, pulse_ir, color="0.35", linewidth=1.0, label="pulse.ir (CT)")
        markerline, stemlines, baseline = ax.stem(
            x_dsamp,
            h_dsamp,
            linefmt="C0-",
            markerfmt="C0o",
            basefmt=" ",
            label="h_dsamp (DT)",
        )
        stemlines.set_alpha(0.8)

        phase_offsets = (np.arange(per_ui, dtype=float) - float(dte.pos)) / per_ui
        ax.axvspan(
            float(np.min(phase_offsets)),
            float(np.max(phase_offsets)),
            color="tab:orange",
            alpha=0.12,
            label="candidate pos main-cursor interval",
        )
        ax.axvline(0.0, color="tab:green", linestyle="--", linewidth=1.0, label=f"selected pos={dte.pos}")
        ax.set_xlabel("Time (UI, selected ts = 0)")
        ax.set_ylabel("Amplitude (V)")
        ax.set_xlim(-5.0, 20.0)
        ax.grid(True)
        ax.legend()
        self._title(ax, "CT Pulse and Selected DT Response", "DT samples are selected at the swept phase positions")
        self._annotate_config(ax)
        self._finish(fig, output)
        return output

    def _plot_dte_coefficients(self, dte: COMDTEStatus, directory: str) -> dict[str, str]:
        """Plot limited and unlimited FFE/DFE coefficients with their limiters."""
        outputs: dict[str, str] = {}
        w_index = np.arange(len(dte.w_lim), dtype=int) - self.cfg.dte.d_w
        b_index = np.arange(1, len(dte.b_lim) + 1, dtype=int)

        # DFE feedback is subtracted from the sampled response. Plot -b so both
        # families use the equalized-pulse sign convention.
        fig, ax, output = self._subplots(directory, "dte_coefficients.png", figsize=(9, 4))
        ax.stem(w_index, dte.w_lim, linefmt="C0-", markerfmt="C0o", basefmt=" ", label="FFE w_lim")
        if len(dte.b_lim):
            ax.stem(b_index, -dte.b_lim, linefmt="C1-", markerfmt="C1s", basefmt=" ", label="DFE -b_lim")
        ax.axvline(0.0, color="tab:green", linestyle="--", linewidth=0.8, label="FFE main")
        ax.set_xlabel("Tap index relative to FFE main cursor")
        ax.set_ylabel("Coefficient")
        ax.grid(True)
        ax.legend()
        self._title(ax, "Limited FFE and DFE Coefficients", "DFE is shown with feedback subtraction sign")
        self._annotate_config(ax)
        self._finish(fig, output)
        outputs["combined"] = output

        fig, ax, output = self._subplots(directory, "unlimited_dte_coefficients.png", figsize=(9, 4))
        lower = np.asarray(self.cfg.dte.w_lower, dtype=float)
        upper = np.asarray(self.cfg.dte.w_upper, dtype=float)
        main_scale = float(dte.w[self.cfg.dte.d_w])
        scaled_lower = lower * main_scale
        scaled_upper = upper * main_scale
        ax.bar(
            w_index,
            scaled_upper - scaled_lower,
            bottom=scaled_lower,
            width=0.8,
            color="0.85",
            edgecolor="0.65",
            label="FFE limiter mask",
            zorder=0,
        )
        unlimited_index = np.arange(len(dte.w), dtype=int) - self.cfg.dte.d_w
        ax.stem(unlimited_index, dte.w, linefmt="C0-", markerfmt="C0o", basefmt=" ", label="w (unlimited)")
        if len(dte.b):
            dfe_lower = -np.asarray(self.cfg.dte.b_upper, dtype=float)
            dfe_upper = -np.asarray(self.cfg.dte.b_lower, dtype=float)
            ax.bar(
                b_index,
                dfe_upper - dfe_lower,
                bottom=dfe_lower,
                width=0.45,
                color="tab:orange",
                alpha=0.18,
                edgecolor="tab:orange",
                label="DFE limiter mask",
                zorder=0,
            )
            ax.stem(b_index, -dte.b, linefmt="C1-", markerfmt="C1s", basefmt=" ", label="DFE -b (unlimited)")
        ax.axvline(0.0, color="tab:green", linestyle="--", linewidth=0.8, label="FFE main")
        ax.set_xlabel("Tap index relative to FFE main cursor")
        ax.set_ylabel("Coefficient")
        ax.set_ylim((-1,1))
        ax.grid(True)
        ax.legend()
        self._title(ax, "Unlimited FFE and DFE with Limiter Masks", "FFE bounds are scaled by the unlimited FFE main coefficient")
        self._annotate_config(ax)
        self._finish(fig, output)
        outputs["unlimited"] = output
        return outputs

    def _plot_dte_matrices(self, dte: COMDTEStatus, directory: str) -> str:
        fig, axes, output = self._subplots(directory, "dte_matrices.png", 1, 2, figsize=(10, 4))
        # The full H has thousands of rows, which hides the main/DFE region.
        row_start = max(0, int(dte.d) - int(self.cfg.dte.d_w) - 2)
        row_stop = min(int(dte.H.shape[0]), int(dte.d) + int(self.cfg.dte.N_b) + 3)
        h_local = np.asarray(dte.H)[row_start:row_stop, :]
        self._plot_matrix_or_vector(
            axes[0],
            h_local,
            f"H rows {row_start}:{row_stop}",
            row_indices=np.arange(row_start, row_stop, dtype=int),
            column_indices=np.asarray(dte.pruned_index, dtype=int),
        )
        self._plot_matrix_or_vector(axes[1], dte.R_nn, "R_nn")
        self._annotate_config(axes[1])
        self._finish(fig, output)
        return output

    @staticmethod
    def _plot_matrix_or_vector(
        ax: Any,
        value: np.ndarray,
        label: str,
        row_indices: Optional[np.ndarray] = None,
        column_indices: Optional[np.ndarray] = None,
    ) -> None:
        array = np.asarray(value)
        if array.ndim == 2:
            # Array row 0 is shown at the top, so row index increases
            # naturally from top to bottom.
            image = ax.imshow(array, aspect="auto", origin="upper")
            ax.figure.colorbar(image, ax=ax)
            ax.set_xlabel("column")
            ax.set_ylabel("row")
            if row_indices is not None:
                ax.set_yticks(np.arange(len(row_indices)))
                ax.set_yticklabels([str(index) for index in row_indices])
            if column_indices is not None:
                ax.set_xticks(np.arange(len(column_indices)))
                ax.set_xticklabels([str(index) for index in column_indices])
        else:
            ax.plot(array)
            ax.set_xlabel("index")
            ax.set_ylabel(label)
            ax.grid(True)
        ax.set_title(label)

    # ------------------------------------------------------------------
    # impairment stages: COMImpStageStatus
    # ------------------------------------------------------------------
    def plot_pre_dte_imp(self, save_path: str | Path = "") -> dict[str, str]:
        """Plot all available pre-DTE PSD, equivalent-channel, and ADC-PMF fields."""
        if self.status.imp is None or self.status.imp.pre_dte is None:
            raise ValueError("COMStatus.imp.pre_dte is not available.")
        return self._plot_imp_stage(self.status.imp.pre_dte, "imp_pre_dte", save_path, pre_dte=True)

    def plot_post_ffe_imp(self, save_path: str | Path = "") -> dict[str, str]:
        """Plot all available post-FFE PSD, equivalent-channel, and ADC-PMF fields."""
        if self.status.imp is None or self.status.imp.post_ffe is None:
            raise ValueError("COMStatus.imp.post_ffe is not available.")
        return self._plot_imp_stage(self.status.imp.post_ffe, "imp_post_ffe", save_path, pre_dte=False)

    def _plot_imp_stage(
        self,
        stage: COMImpStageStatus,
        directory_name: str,
        root: str | Path,
        *,
        pre_dte: bool,
    ) -> dict[str, str]:
        directory = str(Path(root) / directory_name) if root else ""
        outputs: dict[str, str] = {}

        if stage.psd is not None:
            names = ("S_rn", "S_xn", "S_tn", "S_jn", "S_qn", "S_total")
            psd_values = [(name, getattr(stage.psd, name)) for name in names if getattr(stage.psd, name) is not None]
            if psd_values:
                outputs["psd"] = self._plot_psd_group(psd_values, directory, "psd_components.png", f"{directory_name} PSD")

        outputs["imp_proportion"] = self._plot_imp_proportion(stage, directory, directory_name, pre_dte=pre_dte)

        if stage.eq_ch is not None:
            eq = stage.eq_ch
            primary = [("h_dsamp", eq.h_dsamp), ("h_tn", eq.h_tn), ("h_J", eq.h_J)] if pre_dte else [("h_w", eq.h_w), ("h_ISI", eq.h_ISI), ("h_w_J", eq.h_w_J)]
            reference_index = (
                int(self.status.dfe.d) - int(self.cfg.dte.d_w)
                if pre_dte and self.status.dfe is not None
                else int(self.status.dfe.d)
                if not pre_dte and self.status.dfe is not None
                else None
            )
            for name, values in primary:
                if values is not None:
                    outputs[name] = self._plot_sequence(
                        values,
                        directory,
                        f"{name}.png",
                        f"{directory_name} {name}",
                        f"{name} (V)",
                        reference_index=reference_index,
                    )
            xtalk_name, xtalk_values = ("h_XTs_dsamp", eq.h_XTs_dsamp) if pre_dte else ("h_XTs_w", eq.h_XTs_w)
            if xtalk_values:
                outputs[xtalk_name] = self._plot_sequence_group(
                    xtalk_values,
                    directory,
                    f"{xtalk_name}.png",
                    f"{directory_name} {xtalk_name}",
                    reference_index=reference_index,
                )

        if stage.adc_input is not None:
            outputs.update(self._plot_adc_input(stage.adc_input, directory, f"{directory_name} ADC Input"))
        return outputs

    def _plot_imp_proportion(
        self,
        stage: COMImpStageStatus,
        directory: str,
        stage_name: str,
        *,
        pre_dte: bool,
    ) -> str:
        """Plot impairment variance contributions for one processing stage."""
        contributions: list[tuple[str, float]] = []
        if pre_dte and stage.psd is not None:
            for name, label in (
                ("sigma_rn", "receiver noise"),
                ("sigma_xn", "crosstalk"),
                ("sigma_tn", "TX noise"),
                ("sigma_jn", "TX jitter"),
                ("sigma_qn", "ADC quantization"),
            ):
                value = getattr(stage.psd, name, None)
                if value is not None:
                    contributions.append((label, float(value)))
        elif not pre_dte:
            if stage.psd is not None and stage.psd.sigma_ISI is not None:
                contributions.append(("ISI", float(stage.psd.sigma_ISI)))
            adc = stage.adc_input
            if adc is not None:
                for name, label in (("p_XT", "crosstalk"), ("p_DD", "DDJ"), ("p_ga", "Gaussian noise")):
                    pmf = getattr(adc, name, None)
                    if pmf is not None:
                        _, std = self._pmf_moments(pmf)
                        contributions.append((label, std))

        contributions = [(label, sigma) for label, sigma in contributions if np.isfinite(sigma) and sigma >= 0.0]
        if not contributions or not any(sigma > 0.0 for _, sigma in contributions):
            return ""

        labels = [label for label, _ in contributions]
        variance = np.asarray([sigma**2 for _, sigma in contributions], dtype=float)
        percentages = 100.0 * variance / np.sum(variance)
        fig, ax, output = self._subplots(directory, "imp_proportion.png", figsize=(7, 4))
        bars = ax.bar(labels, percentages, color="tab:blue")
        for bar, percentage in zip(bars, percentages):
            ax.text(
                bar.get_x() + bar.get_width() / 2.0,
                bar.get_height(),
                f"{percentage:.1f}%",
                ha="center",
                va="bottom",
                fontsize=9,
            )
        ax.set_ylabel("Variance contribution (%)")
        ax.set_ylim(0.0, max(100.0, float(np.max(percentages)) * 1.18))
        ax.grid(axis="y", alpha=0.35)
        self._title(ax, f"{stage_name} Impairment Proportion", "Percentage of total impairment variance")
        self._annotate_imp_config(ax)
        self._finish(fig, output)
        return output

    def _plot_psd_group(self, psds: list[tuple[str, Any]], directory: str, filename: str, title: str) -> str:
        fig, ax, output = self._subplots(directory, filename)
        for name, psd in psds:
            psd.plot(ax=ax, label=name)
        values = np.concatenate([np.asarray(psd.psd) for _, psd in psds])
        positive_values = values[np.isfinite(values) & (values > 0.0)]
        if positive_values.size:
            ax.set_yscale("log")
            max_value = float(np.max(positive_values))
            min_value = float(np.min(positive_values))
            # Keep a readable logarithmic window without letting numerical
            # noise or isolated tiny bins determine the whole axis.
            lower = max(0.5 * min_value, max_value * 1e-12)
            upper = 2.0 * max_value
            ax.set_ylim(lower, upper)
        self._title(ax, title, "One-sided sampled PSD; CT-equivalent frequency axis")
        self._annotate_config(ax)
        self._finish(fig, output)
        return output

    def _plot_sequence(
        self,
        values: np.ndarray,
        directory: str,
        filename: str,
        title: str,
        ylabel: str,
        *,
        reference_index: Optional[int] = None,
    ) -> str:
        values = np.asarray(values, dtype=float)
        reference = int(np.argmax(np.abs(values))) if reference_index is None else int(reference_index)
        x = (np.arange(len(values)) - reference).astype(float)
        fig, ax, output = self._subplots(directory, filename)
        ax.stem(x, values, basefmt=" ")
        ax.axvline(0.0, color="tab:green", linestyle="--", linewidth=0.8)
        ax.set_xlabel("Discrete time (UI, selected victim cursor = 0)")
        ax.set_ylabel(ylabel)
        ax.set_xlim(-5.0, 20.0)
        ax.grid(True)
        self._title(ax, title)
        self._annotate_config(ax)
        self._finish(fig, output)
        return output

    def _plot_sequence_group(
        self,
        values: list[np.ndarray],
        directory: str,
        filename: str,
        title: str,
        *,
        reference_index: Optional[int] = None,
    ) -> str:
        fig, ax, output = self._subplots(directory, filename)
        for idx, sequence in enumerate(values):
            sequence = np.asarray(sequence, dtype=float)
            reference = int(np.argmax(np.abs(sequence))) if reference_index is None else int(reference_index)
            ax.plot(np.arange(len(sequence)) - reference, sequence, label=f"XT[{idx}]")
        ax.set_xlabel("Discrete time (UI, selected victim cursor = 0)")
        ax.set_ylabel("Amplitude (V)")
        ax.set_xlim(-5.0, 20.0)
        ax.grid(True)
        ax.legend()
        self._title(ax, title)
        self._annotate_config(ax)
        self._finish(fig, output)
        return output

    def _plot_adc_input(self, adc: COMAdcInputPMF, directory: str, title: str) -> dict[str, str]:
        """Plot ADC clipping inputs without overlaying incompatible PMF scales."""
        if adc.method != "pmf_exact":
            return {}

        outputs: dict[str, str] = {}
        fig, axes, output = self._subplots(directory, "adc_input_components.png", 2, 1, figsize=(7, 7), sharex=False)
        p_n = adc.p_n if adc.p_n is not None else adc.p_ga
        if adc.p_s is not None:
            adc.p_s.plot(ax=axes[0], label="p_s")
        if p_n is not None:
            p_n.plot(ax=axes[1], label="p_n")
        self._title(axes[0], f"{title}: signal PMF")
        self._title(axes[1], f"{title}: noise PMF")
        self._annotate_pmf_config(axes[1], adc)
        self._finish(fig, output)
        outputs["adc_input_components"] = output

        fig, axes, output = self._subplots(directory, "adc_input_distribution.png", 2, 1, figsize=(7, 7), sharex=True)
        pdf_ax, cdf_ax = axes
        if adc.p_sn is not None:
            adc.p_sn.plot(ax=pdf_ax, label="p_sn")
            adc.p_sn.plot(ax=cdf_ax, quantity="cdf", label="CDF(p_sn)")

        if adc.V_qc is not None:
            p_qc = self.cfg.imp.P_qc
            for ax in axes:
                ax.axvline(-adc.V_qc, color="tab:red", linestyle="--", linewidth=1.0)
                ax.axvline(adc.V_qc, color="tab:red", linestyle="--", linewidth=1.0)
            pdf_ax.annotate(
                f"V_qc={adc.V_qc:.4g} V\nP_qc={p_qc:.3e}" if p_qc is not None else f"V_qc={adc.V_qc:.4g} V",
                xy=(adc.V_qc, 0.98),
                xycoords=("data", "axes fraction"),
                xytext=(-6, -6),
                textcoords="offset points",
                ha="right",
                va="top",
                color="tab:red",
                fontsize=9,
                bbox={"boxstyle": "round,pad=0.25", "facecolor": "white", "edgecolor": "tab:red", "alpha": 0.9},
            )
            if adc.p_sn is not None:
                cdf_neg = float(np.interp(-adc.V_qc, adc.p_sn.x, adc.p_sn.cdf))
                cdf_ax.scatter([-adc.V_qc], [cdf_neg], color="tab:red", zorder=3)
                cdf_ax.annotate(
                    f"CDF(-V_qc)={cdf_neg:.3e}",
                    xy=(-adc.V_qc, cdf_neg),
                    xytext=(8, 8),
                    textcoords="offset points",
                    ha="left",
                    color="tab:red",
                    fontsize=8,
                )
        cdf_ax.set_ylim(-0.02, 1.02)
        self._title(pdf_ax, f"{title}: p_sn PDF", f"method={adc.method}, delta={adc.delta}")
        self._title(cdf_ax, "p_sn CDF and ADC clipping threshold")
        self._annotate_pmf_config(cdf_ax, adc)
        cdf_ax.set_yscale("log")
        cdf_ax.set_ylim(max(1e-12, float(np.min(adc.p_sn.cdf)) if adc.p_sn is not None else 1e-12), 1.0)
        self._finish(fig, output)
        outputs["adc_input_distribution"] = output
        return outputs

    # ------------------------------------------------------------------
    # calculate_COM_DFE: COMPMFStatus
    # ------------------------------------------------------------------
    def plot_pmf(self, save_path: str | Path = "") -> dict[str, str]:
        """Plot final COM DFE PMF components and the combined CDF tail."""
        if self.status.pmf is None:
            raise ValueError("COMStatus.pmf is not available.")
        pmf_status = self.status.pmf
        directory = str(Path(save_path) / "pmf") if save_path else ""
        outputs: dict[str, str] = {}

        components = [
            (name, getattr(pmf_status, name))
            for name in ("p_ISI", "p_G", "p_DD", "p_XT", "p_qn")
            if getattr(pmf_status, name) is not None
        ]

        for name, pmf in components:
            fig, ax, output = self._subplots(directory, f"{name}.png")
            pmf.plot(ax=ax, label=name)
            mu, std = self._pmf_moments(pmf)
            self._title(ax, name, f"mu={mu:.3e} V, std={std:.3e} V")
            self._annotate_pmf_settings(ax, pmf)
            self._finish(fig, output)
            outputs[name] = output

        fig, ax, output = self._subplots(directory, "pmf_components.png")
        for name, pmf in components:
            pmf.plot(ax=ax, label=name)
        self._title(ax, "Final PMF Components")
        if components:
            self._annotate_pmf_settings(ax, components[0][1])
        self._finish(fig, output)
        outputs["components"] = output

        if pmf_status.p_combined is not None:
            total = pmf_status.p_combined
            fig, axes, output = self._subplots(directory, "combined_cdf.png", 2, 1, figsize=(7, 7), sharex=True)
            pdf_ax, cdf_ax = axes
            total.plot(ax=pdf_ax, label="p_total")
            total.plot(ax=cdf_ax, quantity="cdf", label="CDF(p_total)")

            der0 = float(self.cfg.DER_0)
            y0 = float(total.quantile(der0))
            p_total_y0 = float(np.interp(y0, total.x, total.pmf))
            for axis in axes:
                axis.axvline(y0, color="tab:red", linestyle="--", linewidth=1.0)

            pdf_ax.scatter([y0], [p_total_y0], color="tab:red", zorder=3)
            pdf_ax.annotate(
                f"A_ni={abs(y0):.3e} V",
                xy=(y0, p_total_y0),
                xytext=(8, 8),
                textcoords="offset points",
                color="tab:red",
                fontsize=8,
            )
            cdf_ax.scatter([y0], [der0], color="tab:red", zorder=3)
            cdf_ax.annotate(
                f"DER_0={der0:.3e}\nA_ni={abs(y0):.3e} V",
                xy=(y0, der0),
                xytext=(8, 8),
                textcoords="offset points",
                color="tab:red",
                fontsize=8,
            )
            if pmf_status.y0 is not None:
                cdf_ax.axhline(der0, color="tab:red", linestyle=":", linewidth=0.8)
            cdf_values = np.asarray(total.cdf, dtype=float)
            positive_cdf = cdf_values[np.isfinite(cdf_values) & (cdf_values > 0.0)]
            cdf_ax.set_yscale("log")
            cdf_lower = max(
                1.0e-12,
                float(np.min(positive_cdf)) * 0.5 if positive_cdf.size else 1.0e-12,
            )
            cdf_ax.set_ylim(cdf_lower, 1.0)
            com_text = (
                f"COM={pmf_status.COM:.3f} dB"
                if pmf_status.COM is not None
                else "COM=None"
            )
            self._title(
                pdf_ax,
                "Total PMF PDF",
                f"{com_text}, DER_0={der0:.3e}, A_ni={abs(y0):.3e} V",
            )
            self._title(cdf_ax, "Total PMF CDF", f"{com_text}, DER_0 threshold")
            self._annotate_pmf_settings(cdf_ax, total)
            self._finish(fig, output)
            outputs["combined_cdf"] = output
        return outputs

    # ------------------------------------------------------------------
    # Full single-run orchestration
    # ------------------------------------------------------------------
    def plot_single_run(self, save_path: str | Path = "", path_idx: int = 0) -> dict[str, Any]:
        """Export the first-pass 178A single-run report grouped by pipeline stage."""
        outputs: dict[str, Any] = {"path": self.plot_path(path_idx, save_path)}
        if self.status.run is not None and self.status.dfe is not None:
            outputs["phase_dte"] = self.plot_phase_dte(save_path)
        if self.status.imp is not None and self.status.imp.pre_dte is not None:
            outputs["imp_pre_dte"] = self.plot_pre_dte_imp(save_path)
        if self.status.imp is not None and self.status.imp.post_ffe is not None:
            outputs["imp_post_ffe"] = self.plot_post_ffe_imp(save_path)
        if self.status.pmf is not None:
            outputs["pmf"] = self.plot_pmf(save_path)
        return outputs


__all__ = ["COMReport178A"]
